import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import type {
  PublicFlagFilters,
  PublicFlagsPage,
} from "@/lib/supabase/queries/flags/publicFlagsPageQuery";

import { PublicFlagsQueue } from "../PublicFlagsQueue";

const replaceMock = vi.fn();
const loadPublicFlagsPageMock = vi.fn();

vi.mock("next/navigation", () => ({
  usePathname: () => "/fr/signalements",
  useRouter: () => ({ replace: replaceMock }),
}));

vi.mock("next/link", () => ({
  default: ({
    children,
    href,
    ...props
  }: React.AnchorHTMLAttributes<HTMLAnchorElement> & { href: string }) => (
    <a href={href} {...props}>
      {children}
    </a>
  ),
}));

vi.mock("@/app/[lang]/signalements/actions", () => ({
  loadPublicFlagsPage: (...args: unknown[]) => loadPublicFlagsPageMock(...args),
}));

class IntersectionObserverMock {
  observe = vi.fn();
  disconnect = vi.fn();
  unobserve = vi.fn();
}

global.IntersectionObserver =
  IntersectionObserverMock as unknown as typeof IntersectionObserver;

const longReason = "a".repeat(140);
const initialPage: PublicFlagsPage = {
  items: [
    {
      id: "flag-1",
      publicSlug: "sig-2026-0001",
      kind: "missing-source",
      status: "open",
      reasonText: longReason,
      severity: "medium",
      autoGenerated: false,
      createdAt: "2026-07-23T12:00:00.000Z",
      contributorName: "",
      target: {
        type: "assertion",
        id: "assertion-1",
        entityType: "people",
        entityId: "PPL_BETI",
        fieldPath: "identity.history",
        label: "Beti",
        statement: "Origine du peuple Beti",
      },
    },
  ],
  nextCursor: "next-page",
};

function renderQueue(
  page = initialPage,
  initialFilters: PublicFlagFilters = {}
) {
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: { retry: false, staleTime: Infinity },
    },
  });

  return render(
    <QueryClientProvider client={queryClient}>
      <PublicFlagsQueue initialPage={page} initialFilters={initialFilters} />
    </QueryClientProvider>
  );
}

describe("PublicFlagsQueue", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    window.history.replaceState({}, "", "/fr/signalements");
    vi.useFakeTimers();
    vi.setSystemTime(new Date("2026-07-25T12:00:00.000Z"));
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  // @req REQ-014
  it("renders a privacy-safe, mobile-first linked ledger row", () => {
    renderQueue();

    const row = screen.getByRole("article");
    const link = within(row).getByRole("link", { name: /Beti/i });
    expect(link).toHaveAttribute("href", "/fr/signalements/sig-2026-0001");
    expect(
      within(link).getByText("en cours — examen par l'équipe éditoriale")
    ).toBeInTheDocument();
    expect(within(row).getByText("Peuple")).toBeInTheDocument();
    expect(within(row).getByText("PPL_BETI")).toBeInTheDocument();
    expect(within(row).getByText("Source manquante")).toBeInTheDocument();
    expect(within(row).getByText("Assertion")).toBeInTheDocument();
    expect(within(row).getByText("identity.history")).toBeInTheDocument();
    expect(within(row).getByText("anonyme")).toBeInTheDocument();
    expect(within(row).getByText("il y a 2 jours")).toBeInTheDocument();

    const reason = within(row).getByTestId("flag-reason");
    expect(reason.textContent).toHaveLength(120);
    expect(reason.textContent?.endsWith("…")).toBe(true);
    expect(link.className).toContain("md:");
    expect(link.className).toContain("xl:");
  });

  // @req REQ-014
  it("writes repeated filter values with router.replace", () => {
    renderQueue();

    fireEvent.pointerDown(screen.getByRole("button", { name: /statuts/i }), {
      button: 0,
      ctrlKey: false,
    });
    fireEvent.click(screen.getByRole("menuitemcheckbox", { name: "Ouvert" }));
    fireEvent.click(screen.getByRole("menuitemcheckbox", { name: "Accepté" }));

    expect(replaceMock).toHaveBeenLastCalledWith(
      "/fr/signalements?status=accepted&status=open",
      { scroll: false }
    );
  });

  // @req REQ-014
  it("loads continuation pages through the privacy-safe server action", async () => {
    loadPublicFlagsPageMock.mockResolvedValueOnce({
      items: [],
      nextCursor: null,
    });
    renderQueue();

    fireEvent.click(
      screen.getByRole("button", { name: "Afficher plus de signalements" })
    );

    await vi.waitFor(() => {
      expect(loadPublicFlagsPageMock).toHaveBeenCalledWith(
        expect.objectContaining({ cursor: "next-page" })
      );
    });
  });

  // @req REQ-014
  it("shows the exact empty message and resets active filters", () => {
    window.history.replaceState(
      {},
      "",
      "/fr/signalements?status=rejected&kind=broken-url&target=source"
    );
    renderQueue(
      { items: [], nextCursor: null },
      {
        statuses: ["rejected"],
        kinds: ["broken-url"],
        targetTypes: ["source"],
      }
    );

    expect(
      screen.getByText("aucun signalement ne correspond à ces filtres")
    ).toBeInTheDocument();

    fireEvent.click(screen.getByRole("button", { name: "réinitialiser" }));

    expect(replaceMock).toHaveBeenLastCalledWith("/fr/signalements", {
      scroll: false,
    });
  });

  // @req REQ-014
  it("truncates reasons at 120 Unicode code points without splitting emoji", () => {
    const emojiReason = `${"a".repeat(118)}😀😀😀`;
    renderQueue({
      ...initialPage,
      items: [{ ...initialPage.items[0], reasonText: emojiReason }],
    });

    const reason = screen.getByTestId("flag-reason").textContent ?? "";
    expect(Array.from(reason)).toHaveLength(120);
    expect(reason).toBe(`${"a".repeat(118)}😀…`);
  });
});
