"""The ten result pages. Copy comes from the approved boards
(docs/design/mockups/search/*.dc.html) and from the corpus on recette; the
short titles and durations are illustrative, and say so on the canvas."""

CONV_NAMES = ("Aucun de ces noms n'est faux.",
              "Ils ne viennent simplement pas du même endroit : celui qu'un peuple se donne, ceux que ses voisins lui donnent, celui qu'une administration a écrit un jour.")

P_MALINKE = dict(type="anecdote", img="malinke", about="Malinké", tier="referenced",
                 headline="Malinké, Mandinka, Mandingo, Maninka : un seul nom, réfracté par les routes de la dispersion.",
                 alt="Toit de chaume et falaises de grès près de Siby, dans les monts du Manden",
                 credit="Ralf Steinberger · CC BY 2.0")
P_BAMBARA = dict(type="anecdote", img="bambara", about="Bambara", tier="referenced",
                 headline="Bambara veut probablement dire « ceux qui refusent ».",
                 alt="Coiffe Chi Wara, peuple bamana, Mali",
                 credit="Daderot · CC0")
P_DIOULA = dict(type="anecdote", img="dioula", about="Dioula", tier="referenced",
                headline="Les Dioula portent pour nom de peuple un nom de métier.",
                alt="La Grande Mosquée de Bobo-Dioulasso",
                credit="Angeline A. van Achterberg · CC BY-SA 4.0")
PROV_OR = dict(type="proverbe", lang="bambara", iso="bm",
               text="L'or et l'argent sont périssables, mais les relations humaines restent.",
               original="Sanu ni wari bè ban, nga mogoya te ban",
               meaning="La richesse peut disparaître, la fraternité est plus durable.",
               origin="Publié en 2008 par un juriste malien, université de Fribourg · Référencée")
PROV_GRAINE = dict(type="proverbe", lang="bambara", iso="bm",
                   text="Le propre de la graine est de lever, celui du fruit est de mûrir, celui de l'homme est de comprendre.",
                   original="Dànnifen ye wilita ye, jiriden ye mofen ye, mogoya ye hakili ye",
                   meaning="La réflexion et la sagesse sont ce qui distingue l'être humain.",
                   origin="Publié en 2008, université de Fribourg · Référencée")
P_NIGERIA = dict(type="anecdote", img="nigeria", about="Nigeria", tier="referenced",
                 headline="Le Nigeria a été nommé dans une tribune de presse.",
                 alt="Flora Shaw (Lady Lugard) et Frederick Lugard, 1908",
                 credit="Arnold Wright · domaine public")

CASES = [
    dict(
        id="mande", file="Mande", name="Mandé", name_plain="Mandé", q="mandé", result_state="exact",
        title="Mandé — le nom cherché vient du dehors",
        verdict="Un nom venu du dehors.",
        sub="Les peuples qu'il désigne s'appellent Maninka, Bambara, Dioula, Mandinka, Soninké, Kpelle, Mende — selon le groupe et le pays.",
        lens=[("Shorts", 6), ("Images", 5), ("Jeux", True), ("Fiches", 34)],
        forms=[("Mandingue", "français colonial", ""), ("Mandingo", "anglais colonial", ""), ("Manding", "dans les livres", ""), ("Mandé", "votre recherche", "you")],
        shorts=dict(sub="Chacun répond à « D'où vient le nom… ? » en moins d'une minute.",
                    items=[("Mandé", "0:41", None), ("Keïta", "0:38", "Nom de famille"), ("Malinké", "0:44", None), ("Bambara", "0:39", None), ("Dioula", "0:36", None), ("Mandinka", "0:40", None)]),
        origins=dict(sub="Chaque forme, d'où elle vient, et qui l'emploie encore.", cards=[
            ("Mandé", "votre recherche", "Du <strong>Manden</strong> — Mali méridional, Guinée nord-orientale — qui donne son nom à l'ensemble.", None, "referenced", "you"),
            ("Mandingue", "français colonial", "L'équivalent français de <strong>Mandingo</strong>.", None, "referenced", ""),
            ("Mandingo", "anglais colonial", "La forme employée par les colonisateurs britanniques.", "encore employée en Gambie et en Sierra Leone.", "referenced", ""),
            ("Manding", "dans les livres", "La forme qu'on lit le plus souvent dans les livres, pour parler de l'ensemble.", None, "referenced", ""),
        ]),
        tiles=dict(title="Ce que les peuples se donnent", sub="Le nom que chacun porte de lui-même.",
                   items=[("Maninka", "Guinée, Mali"), ("Bambara", "Mali"), ("Dioula", "Burkina, Côte d'Ivoire"), ("Mandinka", "Gambie, Sénégal"), ("Soninké", "Mali, Mauritanie"), ("Kpelle", "Libéria, Guinée")],
                   link="Les 31 peuples mandé →"),
        plates=[P_MALINKE, P_BAMBARA, PROV_OR, P_DIOULA],
        quiz=dict(q="D'où vient le nom « Mandé » ?", options=["Du Manden, entre le sud du Mali et le nord-est de la Guinée", "D'un mot anglais de l'époque coloniale", "D'un nom de métier"], count="Une question tirée de cette page"),
        image=dict(img="mansa", caption="Mansa Musa, le pèlerinage de 1324", tier="referenced", source="Northwestern University Library",
                   licence="CC BY-SA 4.0 pour la part humaine : sélection, composition, légende", alt="Illustration générée : Mansa Musa en pèlerinage, 1324"),
        fiches=[("Famille", "Mandé", "31 peuples"), ("Peuple", "Maninka", "Guinée, Mali"), ("Peuple", "Bambara", "Mali"), ("Peuple", "Dioula", "Burkina, Côte d'Ivoire")],
        band=dict(silences=[("Aucune attestation datée", "Nous ne datons aucune de ces attestations : on ne sait pas depuis quand chaque forme est écrite.")], conv=CONV_NAMES),
        order=["origins", "tiles", "plates", "quiz", "images", "fiches"],
    ),
    dict(
        id="peul", file="Peul", name="Peul", name_plain="Peul", q="peul", result_state="exact",
        title="Peul — sept noms extérieurs, dont un péjoratif",
        verdict="Sept noms venus du dehors. Aucun n'est le sien.",
        sub="Ils se disent <strong>Fulbe</strong> au pluriel, <strong>Pullo</strong> au singulier.",
        lens=[("Shorts", 4), ("Images", 3), ("Jeux", True), ("Fiches", 11)],
        forms=[("Fulbe", "leur nom", "own"), ("Peul", "votre recherche", "you"), ("Fulani", "haoussa", ""), ("Fula", "mandingue", ""), ("Fellata", "péjoratif", "bad")],
        shorts=dict(sub="Chacun répond à « D'où vient le nom… ? » en moins d'une minute.",
                    items=[("Peul", "0:43", None), ("Fulbe", "0:40", None), ("Fulani", "0:39", None), ("Pulaar", "0:42", "La langue")]),
        origins=dict(sub="Chaque forme, sa langue d'origine, et qui l'emploie aujourd'hui.", cards=[
            ("Peul <span style=\"font-weight: 400; color: #746557;\">/ Peulh</span>", "votre recherche", "Vient du wolof <em>Pel</em>, adopté par les colonisateurs français.", "usage dominant en français.", "referenced", "you"),
            ("Fulani", "haoussa", "La forme haoussa, courante au Nigeria et en anglais.", "dominant en anglais, surtout au Nigeria.", "referenced", ""),
            ("Fula <span style=\"font-weight: 400; color: #746557;\">/ Fulah</span>", "mandingue", "Vient du mandingue.", None, "referenced", ""),
            ("Fellata <span style=\"font-weight: 400; color: #746557;\">/ Fallatah</span>", "péjoratif", "Terme arabe (Tchad, Soudan), parfois associé aux Peuls en pèlerinage vers La Mecque. Considéré comme péjoratif dans certains contextes, associé à des stéréotypes de migrants indésirables.", None, "referenced", "bad"),
            ("Fulbe", "leur nom", "Le nom qu'ils se donnent, au pluriel ; <strong>Pullo</strong> au singulier.", "les communautés elles-mêmes, et les travaux académiques.", "referenced", "own"),
        ]),
        plates=[
            dict(type="anecdote", img="peul", about="Fulɓe", tier="official",
                 headline="Le même peuple change de nom à chaque frontière qu'il traverse.",
                 alt="Gare de Dakar, 1972 : un homme coiffé d'un chapeau de paille peul", credit="Fred van der Kraaij · CC BY-SA 4.0"),
            dict(type="anecdote", img="fulbe", about="Fulbe", tier="referenced",
                 headline="Les Fulbe portent quatre noms internationaux, et aucun des quatre n'est le leur.",
                 alt="Couverture kaasa tissée à la main, style peul", credit="Cleveland Museum of Art · CC0"),
            dict(type="proverbe", lang="peul", iso="fuc", text="La langue est l'ennemie de son propriétaire.",
                 original="ɗemngal ko ganyo jooma mum",
                 origin="Proverbe peul du Fouladou (Sénégal), publié en 1987 avec son texte original · Référencée"),
        ],
        quiz=dict(q="Quel nom les Peuls se donnent-ils ?", options=["Fulbe", "Fulani", "Fula"], count="Une question tirée de cette page"),
        prose=dict(title="Ce que ces noms posent problème", tier="referenced", paras=[
            "Aucun de ces noms n'est celui qu'ils se donnent. Et <strong>Fulani</strong> sert souvent à ne désigner que les éleveurs nomades, en oubliant tous ceux qui vivent installés."]),
        fiches=[("Peuple", "Peul", "Fulbe"), ("Famille", "Atlantique", "famille de langues"), ("Langue", "La langue peule", "pulaar à l'ouest, fulfulde à l'est"), ("Pays", "Les pays de présence", "du Sénégal au Soudan")],
        band=dict(silences=[("Aucune attestation datée", "Nous ne datons aucune de ces attestations : on ne sait pas depuis quand chaque forme est écrite.")],
                  conv=("Le nom qui compte le plus est celui qu'ils se donnent.", "Personne n'est mieux placé qu'eux pour raconter leur histoire. Le chercher demande du travail, et ce travail produit des erreurs.")),
        order=["origins", "plates", "quiz", "problem", "fiches"],
    ),
    dict(
        id="fang", file="Fang", name="Fang", name_plain="Fang", q="pahouin", result_state="exact",
        title="Fang — le cas ordinaire, aucune forme qualifiée",
        verdict="Trois noms européens, un seul mot au départ.",
        sub="Ils se disent <strong>Fang</strong>, prononcé fàŋ. Les trois autres viennent de voisins qui les avaient entendus le dire.",
        lens=[("Shorts", 4), ("Images", 1), ("Jeux", True), ("Fiches", 5)],
        forms=[("Fang", "leur nom", "own"), ("Pahouin", "votre recherche", "you"), ("Pangwe", None, ""), ("Pamue", None, ""), ("Mpangwe", None, "")],
        shorts=dict(sub="Chacun répond à « D'où vient le nom… ? » en moins d'une minute.",
                    items=[("Pahouin", "0:40", None), ("Fang", "0:42", None), ("Beti", "0:37", "Peuple voisin"), ("Bulu", "0:39", "Peuple voisin")]),
        origins=dict(sub=None,
                     lede="Les trois noms européens viennent d'un même mot, <strong>Mpangwe</strong>, par lequel les peuples de la côte de l'estuaire du Gabon désignaient leurs voisins de l'intérieur : ils les avaient entendus se nommer <em>fang</em> et l'avaient adapté à leur propre langue.",
                     cards=[
                         ("Pahouin", "votre recherche", "La forme française, reprise des intermédiaires de la côte vers le milieu du XIX<sup>e</sup> siècle.", "un nom colonial, repris surtout pour parler de l'histoire du nom.", "referenced", "you"),
                         ("Pangwe", "allemand", "La forme allemande du même mot.", "un nom colonial.", "referenced", ""),
                         ("Pamue", "espagnol", "La forme espagnole du même mot.", "un nom colonial.", "referenced", ""),
                         ("Mpangwe", "la côte", "Le mot des peuples de la côte pour leurs voisins de l'intérieur, adapté de <em>fang</em>.", None, "referenced", ""),
                         ("Fang", "leur nom", "Le nom qu'ils se donnent, prononcé fàŋ. <em>Fan</em> en est une graphie ancienne — une orthographe du même nom, pas un autre nom.", "la forme en usage dans la littérature en français.", "referenced", "own"),
                     ]),
        plates=[dict(type="anecdote", img="fang", about="Fang", tier="unverified",
                     headline="Les Fang ont laissé courir une réputation de cannibales pour tenir les étrangers à distance.",
                     alt="Eyema byeri, figure de gardien de reliquaire", credit="Artiste okak-fang · CC0")],
        quiz=dict(q="Qui a fait du mot Mpangwe le nom « Pahouin » ?", options=["Les Français", "Les Allemands", "Les Espagnols"], count="Une question tirée de cette page"),
        prose=dict(title="Ce que ces noms posent problème", tier="referenced", paras=[
            "Ces noms étaient collectifs : ils rangeaient sous une seule étiquette les Fang et des peuples voisins apparentés, les Bulu et les Beti.",
            "<strong>Pahouin</strong> est parfois tenu pour péjoratif : il s'est chargé de stéréotypes coloniaux, nés de la découverte de boîtes reliquaires contenant des os d'ancêtres."]),
        fiches=[("Peuple", "Fang", "Gabon, Guinée équatoriale, Cameroun"), ("Famille", "Bantu", "famille de langues"), ("Peuple", "Bulu", "peuple voisin"), ("Peuple", "Beti", "peuple voisin")],
        band=dict(silences=[("Aucune attestation datée", "Nous situons l'emprunt européen au milieu du XIX<sup>e</sup> siècle, mais ne datons aucune de ces formes une par une."),
                            ("Ce que chaque nom veut dire", "Nous disons d'où vient chaque forme, pas ce qu'elle signifiait dans la langue de ceux qui l'ont écrite.")], conv=CONV_NAMES),
        order=["origins", "plates", "quiz", "problem", "fiches"],
    ),
    dict(
        id="bassa", file="Bassa", name="Bassa", name_plain="Bassa", q="bassa", result_state="exact",
        title="Bassa — un nom, trois peuples sans parenté",
        verdict="Trois peuples portent ce nom. Ils ne sont pas parents.",
        sub="Nous les rangeons dans trois familles de langues différentes, à des milliers de kilomètres les uns des autres.",
        lens=[("Shorts", 2), ("Images", 1), ("Jeux", True), ("Fiches", 4)],
        forms_title="Lequel cherchez-vous ?", forms_sub="Trois peuples, trois familles de langues.",
        forms=[("Bassa", "krou · Liberia", ""), ("Basaa", "bantu · Cameroun", ""), ("Bassa Nge", "bénoué-congo · Nigeria", "")],
        shorts=dict(sub="Un short par peuple : le même nom ne fait pas une parenté.",
                    empty=("D’où vient le nom « Bassa » ?", "Pas encore de short sur les Bassa de la famille krou.", "Proposer une source →"),
                    items=[("Basaa", "0:42", "Basaa · Cameroun"), ("Bassa Nge", "0:38", "Bassa Nge · Nigeria")]),
        people=dict(title="Les trois peuples", sub=None, items=[
            ("Bassa", "famille krou · Liberia, Côte d'Ivoire, Sierra Leone", "Ils se disent <strong>Bassa</strong>. Les voyageurs et les missionnaires européens ont écrit ce nom sans jamais dire ce qu'il voulait dire."),
            ("Basaa", "famille bantu · Cameroun", "Ils se disent <strong>Bàsáa</strong>. « Bassa » est la façon dont l'administration coloniale l'a écrit."),
            ("Bassa Nge", "famille bénoué-congo · Nigeria", "Le nom a été fixé par l'administration britannique, pour les distinguer des <strong>Bassa Komu</strong> — un autre peuple, arrivé presque en même temps."),
        ]),
        prose=dict(title="Pourquoi le même nom ?", tier="referenced", paras=[
            "Nous ne l'expliquons pas, et aucune source que nous citons ne le fait.",
            "Ce qu'on peut dire : dans <strong>deux cas sur trois</strong>, l'orthographe « Bassa » ne vient pas du peuple. C'est la façon dont une administration extérieure a écrit son nom. Une partie de la confusion a été fabriquée en chemin."]),
        prose2=dict(title="Vous cherchiez peut-être <em>Bassari</em> ?", paras=[
            "Un autre peuple encore, au Sénégal et en Guinée. Le nom se ressemble ; nous ne lui connaissons aucun lien avec les trois ci-dessus."]),
        plates=[dict(type="anecdote", img="bassange", about="Bassa Nge", tier="referenced",
                     headline="Un nom colonial a, pour une fois, empêché une confusion au lieu d'en créer une.",
                     alt="Lokoja et le fleuve vus du mont Patti, Nigeria", credit="Dotun55 · CC BY-SA 4.0")],
        quiz=dict(q="Les trois peuples Bassa sont-ils parents ?", options=["Non : aucune source que nous citons ne les relie", "Oui, ils parlent la même langue", "Oui, ils viennent tous du Cameroun"], count="Une question tirée de cette page"),
        fiches=[("Peuple", "Bassa", "Liberia"), ("Peuple", "Basaa", "Cameroun"), ("Peuple", "Bassa Nge", "Nigeria"), ("Peuple", "Bassari", "Sénégal, Guinée")],
        band=dict(silences=[("Aucune attestation datée", "Nous ne datons aucune de ces graphies : on ne sait pas depuis quand chacune est écrite."),
                            ("Pourquoi le même nom", "Aucune source que nous citons ne l'explique.")],
                  conv=("Un nom partagé n'est pas une parenté.", "Deux peuples peuvent porter le même nom sans avoir rien en commun — et deux peuples proches peuvent porter des noms qui ne se ressemblent pas.")),
        order=["peoples", "shared-name", "plates", "quiz", "near-name", "fiches"],
    ),
    dict(
        id="ekpeye", file="Ekpeye", name="Ekpeye", name_plain="Ekpeye", q="ekpeye", result_state="widened", thin=True,
        title="Ekpeye — le cas pauvre, silences déclarés",
        verdict="Un seul nom, porté de l'intérieur comme de l'extérieur.",
        sub="Le nom Ekpeye est l'unique dénomination usitée, tant en interne que dans les sources officielles et académiques nigérianes.",
        lens=[("Shorts", 2), ("Images", 1), ("Jeux", True), ("Fiches", 2)],
        forms=[("Ekpeye", "leur nom, et celui de tous", "own")],
        shorts=dict(sub=None,
                    empty=("D’où vient le nom « Ekpeye » ?", "Aucune source lue ne dit d'où vient ce nom. Pas de short sans réponse.", "Vous savez ? Proposer une source →"),
                    note="Autour d'Ekpeye — la même famille de langues, pas le même nom",
                    items=[("Igbo", "0:41", "Bénoué-Congo"), ("Yoruba", "0:44", "Bénoué-Congo")]),
        facts=dict(title="Ce que nous savons", items=[("Famille", "Bénoué-Congo — branche igboïde"), ("Région", "Ekpeyeland, Ahoada, delta du Niger"), ("Pays", "Nigeria"), ("Sources", "6")]),
        plates_sub="Rien encore sur Ekpeye. Autour : le Nigeria, son pays.",
        plates=[P_NIGERIA],
        quiz=dict(q="Dans quelle famille de langues rangeons-nous l'ekpeye ?", options=["Bénoué-Congo", "Atlantique", "Mandé"], count="Une question tirée de cette page"),
        fiches=[("Peuple", "Ekpeye", "Nigeria"), ("Pays", "Nigeria", "le pays")],
        band=dict(silences=[("Aucune autre appellation", "Nous n'avons trouvé aucun autre nom donné de l'extérieur."),
                            ("Origine du nom non documentée", "Aucune source lue ne dit d'où il vient, ni ce qu'il voulait dire."),
                            ("Aucune attestation datée", "On ne sait pas depuis quand ce nom est écrit.")],
                  conv=("Appeler quelqu'un comme il s'appelle ne retire rien à personne.", "C'est le geste le moins coûteux qui soit — et ici, le nom que les Ekpeye se donnent est celui que tout le monde emploie."),
                  invite="Vous connaissez ce nom mieux que nous ?", invite_sub="Si vous avez une source sur son origine, elle sera lue."),
        order=["atlas-holds", "plates", "quiz", "fiches"],
    ),
    dict(
        id="nigeria", file="Nigeria", name="Nigeria", name_plain="Nigeria", q="nigeria", result_state="exact", kind="Pays",
        title="Nigeria — un pays nommé dans un journal",
        verdict="Un nom proposé dans un journal, en 1897.",
        sub="« Niger », le fleuve, et le suffixe latin « -ia », le pays. Flora Shaw l'a suggéré ; Lord Lugard l'a officialisé en 1914.",
        lens=[("Shorts", 5), ("Images", 1), ("Jeux", True), ("Fiches", 74)],
        forms_title="Les appellations", forms_sub="Le nom, puis ceux qui l'ont précédé ou suivi.",
        forms=[("Nigeria", "votre recherche · 1914", "you"), ("Niger Area", "1897", ""), ("Fédération du Nigeria", "1960", ""), ("République fédérale", "depuis 1963", ""), ("Protectorats du Nord et du Sud", "XIX<sup>e</sup> siècle", "")],
        shorts=dict(sub="Chacun répond à « D'où vient le nom… ? » en moins d'une minute.",
                    items=[("Nigeria", "0:35", None), ("Niger", "0:40", "Le fleuve"), ("Yoruba", "0:44", "Peuple du Nigeria"), ("Igbo", "0:41", "Peuple du Nigeria"), ("Haoussa", "0:38", "Peuple du Nigeria")]),
        origins=dict(title="D'où il vient", sub=None, cards=[
            ("Nigeria", "votre recherche", "Proposé le 8 janvier 1897 par Flora Shaw, correspondante coloniale du Times, pour désigner d'un seul mot la « Niger Area » administrée par la Royal Niger Company. Officialisé seize ans plus tard, en 1914, par Lord Lugard, lors de l'unification des protectorats du Nord et du Sud.", ("Une nuance", "Shaw a suggéré le nom, elle ne l'a pas imposé."), "referenced", "you"),
            ("Nigerian", "avant 1897 ?", "Des occurrences antérieures sont signalées chez William Cole (1862) et Richard Burton (1863), sans qu'il soit établi qu'elles soient contemporaines plutôt qu'ajoutées à l'édition.", None, "referenced", ""),
            ("Les noms officiels", "1914 · 1960 · 1963", "Protectorats du Nord et du Sud Nigeria au XIX<sup>e</sup> siècle ; Nigeria en 1914 ; Fédération du Nigeria de 1960 à 1963 ; République fédérale du Nigeria depuis 1963.", None, None, ""),
            ("Avant le nom", "sans nom unifié", "Sultanats haoussa, empire Kanem-Bornou, royaume d'Oyo, Ile-Ife, chefferies igbo, royaumes ijaw, royaume du Bénin.", None, None, ""),
        ]),
        tiles=dict(title="Les peuples du Nigeria", sub="Les plus nombreux d'abord — chacun avec son propre nom. UNFPA, 2025.",
                   items=[("Hausa-Fulani", "36 %"), ("Yoruba", "15,5 %"), ("Igbo", "15,2 %"), ("Ijaw", "—"), ("Kanuri", "—"), ("Tiv", "—")],
                   link="Les peuples du Nigeria →"),
        plates=[P_NIGERIA],
        quiz=dict(q="Qui a proposé le nom « Nigeria », en 1897 ?", options=["Flora Shaw, dans le Times", "Lord Lugard, en unifiant les protectorats", "La Royal Niger Company"], count="Une question tirée de cette page"),
        prose=dict(title="Ce que ce nom ne dit pas", tier="referenced", paras=[
            "C'est un nom colonial qui ne reflète aucune appellation précoloniale — et l'attribution elle-même demande une nuance : Shaw a suggéré le nom, elle ne l'a pas imposé."]),
        fiches=[("Pays", "Nigeria", "237,5 millions d'habitants · UNFPA 2025"), ("Peuple", "Yoruba", "Nigeria, Bénin"), ("Peuple", "Igbo", "Nigeria"), ("Peuple", "Hausa-Fulani", "Nigeria, Niger")],
        band=dict(silences=[("Les attestations antérieures", "On ne sait pas si « Nigerian », chez Cole (1862) et Burton (1863), date de ces années ou a été ajouté à l'édition.")],
                  conv=("Le nom est jeune ; les peuples qu'il rassemble sont bien plus anciens.", "Sultanats haoussa, Kanem-Bornou, Oyo, Ife, Bénin : ce territoire avait des noms bien avant d'en avoir un seul.")),
        order=["origins", "tiles", "plates", "quiz", "problem", "fiches"],
    ),
    dict(
        id="lingala", file="Lingala", name="Lingala", name_plain="Lingala", q="lingala", result_state="exact", kind="Langue",
        title="Lingala — un nom de missionnaires, une langue plus ancienne",
        verdict="Un nom de missionnaires, pour une langue bien plus ancienne.",
        sub="La langue vient du bobangi, grande langue commerciale du fleuve Congo. Le nom date du début du XX<sup>e</sup> siècle — les fiches hésitent entre 1901 et 1903.",
        lens=[("Shorts", 4), ("Images", 1), ("Jeux", True), ("Fiches", 4)],
        forms=[("Lingala", "votre recherche", "you"), ("Ngala", None, ""), ("Losengo", None, ""), ("Bangala", "le nom d'avant", "")],
        shorts=dict(sub="Chacun répond à « D'où vient le nom… ? » en moins d'une minute.",
                    items=[("Lingala", "0:38", None), ("Bangala", "0:40", None), ("Bobangi", "0:36", "La langue d'origine"), ("Congo", "0:44", "Le fleuve")]),
        origins=dict(sub="Deux fiches racontent ce nom ; elles ne donnent pas la même date.", cards=[
            ("Lingala", "votre recherche", "Créé par les missionnaires catholiques CICM (Scheutistes) pour désigner la langue standardisée issue du bobangi, en remplacement du terme <em>Bangala</em>, jugé trop ambigu.", ("Quand", "vers 1901-1902 selon une fiche ; 1903 pour le premier usage documenté selon une autre."), "referenced", "you"),
            ("Bangala", "le nom d'avant", "« Peuple de la Mongala », en lingala. Dès 1877, les Européens nomment ainsi les habitants de la zone du poste de Bangala-Station (actuelle Nouvelle-Anvers) — un nom que ces peuples n'employaient pas.", None, "referenced", ""),
            ("Ngala · Losengo", "autres noms", "Deux autres noms que nous enregistrons pour la même langue.", None, "official", ""),
        ]),
        plates=[dict(type="anecdote", img="lingala", about="Lingala", tier="referenced",
                     headline="Le nom du lingala a été inventé par des missionnaires belges.",
                     alt="Le vapeur Livingstone à Baringa, Congo, vers 1900-1915", credit="Auteur inconnu · domaine public")],
        quiz=dict(q="Sur quelle langue le lingala standardisé a-t-il été bâti ?", options=["Le bobangi", "Le kikongo", "Le swahili"], count="Une question tirée de cette page"),
        prose=dict(title="Combien de locuteurs ?", tier="referenced", paras=[
            "Les fiches ne s'accordent pas : 10 à 25 millions de personnes en RDC et en République du Congo selon l'une ; environ 40 millions, dont 20 millions de locuteurs maternels, selon une autre.",
            "Nous ne tranchons pas."]),
        fiches=[("Langue", "Lingala", "famille bantu · lin"), ("Peuple", "Lingala", "RDC, Congo"), ("Peuple", "Ngala", "RDC, Congo"), ("Famille", "Bantu", "famille de langues")],
        band=dict(silences=[("La date exacte du nom", "1901-1902 selon une fiche, 1903 selon une autre : nous ne tranchons pas."),
                            ("Le nombre de locuteurs", "Les chiffres des fiches ne s'accordent pas.")],
                  conv=("Une langue n'attend pas son nom pour exister.", "Le bobangi se parlait sur le fleuve bien avant l'arrivée des Européens ; le nom est venu après.")),
        order=["origins", "plates", "quiz", "problem", "fiches"],
    ),
    dict(
        id="traore", file="Traore", name="Traoré", name_plain="Traoré", q="traoré", result_state="exact", kind="Nom de famille",
        title="Traoré — un nom de clan, une transcription coloniale",
        verdict="Un nom de clan, transcrit par l'administration coloniale.",
        sub="La forme mandingue est <strong>Tarawele</strong> ; Traoré en est la transcription coloniale francophone. Aucune étymologie ne fait consensus.",
        lens=[("Shorts", 4), ("Images", 2), ("Jeux", True), ("Fiches", 4)],
        forms=[("Traoré", "votre recherche", "you"), ("Tarawele", "la forme mandingue", "own"), ("Taraore", None, "")],
        shorts=dict(sub="Chacun répond à « D'où vient le nom… ? » en moins d'une minute.",
                    items=[("Traoré", "0:40", None), ("Keïta", "0:38", "Nom de famille"), ("Diarra", "0:37", "Son allié"), ("Bambara", "0:39", "Le peuple")]),
        origins=dict(title="D'où il vient", sub=None, cards=[
            ("Tarawele", "la forme mandingue", "Le nom du clan. Dans la geste de Soundiata, <strong>Tiramaghan Traoré</strong>, général de Soundiata et conquérant du Kaabu, est donné comme son ancêtre éponyme.", ("Selon", "la tradition orale, rapportée par D. T. Niane (1960)."), "referenced", "own"),
            ("Traoré", "votre recherche", "La transcription coloniale francophone de <em>Tarawele</em>. Aucune étymologie ne fait consensus.", None, "referenced", "you"),
            ("Taraore", "autre graphie", "Une troisième transcription du même nom.", None, None, ""),
        ]),
        tiles=dict(title="Ce que ce nom relie", sub="Un jamu est un nom de clan patrilinéaire.",
                   items=[("Diarra", "allié à plaisanterie"), ("Diop", "en pays wolof, un Traoré y est reçu comme frère"), ("Bambara", "le peuple auquel nous le rattachons"), ("Mali · Burkina · Côte d'Ivoire", "Guinée, Sénégal")]),
        plates_sub="Rien encore sur Traoré lui-même. Autour : les Bambara, le peuple auquel nous le rattachons.",
        plates=[P_BAMBARA, PROV_GRAINE],
        quiz=dict(q="Quelle est la forme mandingue du nom Traoré ?", options=["Tarawele", "Diarra", "Kaabu"], count="Une question tirée de cette page"),
        prose=dict(title="Un statut qui change d'une région à l'autre", tier="referenced", paras=[
            "Le statut attaché au nom varie d'une aire à l'autre : <em>hɔ́rɔn</em>, puis <em>tontigi</em> chez les Bamana et les Maninka, puis <em>nùmu</em> (forgeron) chez les Kagoro et les Wassoulounké."]),
        fiches=[("Nom", "Traoré", "Mali, Burkina, Côte d'Ivoire, Guinée, Sénégal"), ("Nom", "Diarra", "son allié"), ("Peuple", "Bambara", "Mali"), ("Nom", "Keïta", "un autre jamu mandé")],
        band=dict(silences=[("Aucune étymologie retenue", "Aucune ne fait consensus ; nous n'en retenons aucune."),
                            ("Aucun totem connu", "Nous ne connaissons pas de totem attaché à ce nom.")], conv=CONV_NAMES),
        order=["origins", "tiles", "plates", "quiz", "problem", "fiches"],
    ),
    dict(
        id="introuvable", file="Introuvable", name="Mandinka", name_plain="Introuvable", q="mandinké", result_state="typo", thin=True,
        title="Introuvable — une faute de frappe mène au bon article",
        eyebrow="Aucune fiche ne porte exactement « mandinké »",
        verdict="Vouliez-vous dire Mandinka ?", verdict_plain=True,
        sub="C'est l'un des noms que les peuples mandé se donnent, en Gambie et au Sénégal.",
        lens=[("Shorts", 3), ("Images", 1), ("Fiches", 3)],
        forms_title="Formes proches trouvées", forms_sub=None,
        forms=[("Mandinka", "le nom que se donnent les Mandé de Gambie", "you"), ("Malinké", "un peuple mandé", ""), ("Mandingue", "français colonial", "")],
        shorts=dict(sub="Sur les formes proches.", items=[("Mandinka", "0:40", None), ("Malinké", "0:44", None), ("Mandé", "0:41", None)]),
        plates=[P_MALINKE],
        fiches=[("Peuple", "Mandinka", "Gambie, Sénégal"), ("Peuple", "Malinké", "Mali, Guinée"), ("Famille", "Mandé", "31 peuples")],
        further=["Parcourir les peuples", "Les familles de langues"],
        order=["plates", "fiches"],
    ),
    dict(
        id="inconnu", file="Inconnu", name="Kossiwa", name_plain="Inconnu", q="kossiwa", result_state="unknown", thin=True,
        title="Inconnu — un nom que nous ne connaissons pas",
        verdict="Nous ne connaissons pas ce nom.", verdict_plain=True,
        sub="Ce n'est pas une réponse : c'est un aveu. Nous documentons 774 peuples, et il en manque.",
        lens=[("Shorts", 3)],
        shorts=dict(sub=None,
                    empty=("D’où vient le nom « Kossiwa » ?", "Personne ne nous l'a encore raconté.", "Nous parler de ce nom →"),
                    note="Les plus récents — sans rapport avec « kossiwa »",
                    items=[("Nigeria", "0:35", None), ("Lingala", "0:38", None), ("Afrique", "0:40", None)]),
        band=dict(conv=("Personne n'est mieux placé que vous pour raconter votre histoire.", "C'est pour cela que ce champ existe, et que toute correction est lue."),
                  invite="Ce nom est le vôtre ?",
                  invite_sub="Si ce nom est le vôtre, ou celui d'un peuple, d'une langue ou d'un lieu que vous connaissez, dites-le-nous. C'est comme ça que notre projet grandit.",
                  button="Nous parler de ce nom"),
        further=["Parcourir les peuples", "Les familles de langues"],
        order=[],
    ),
]
