import type { SupabaseClient } from "@supabase/supabase-js";
import { z } from "zod";

import { logger } from "@/lib/api/logger";
import type { FlagRow } from "@/types/module-zero";

export type PublicFlagStatus = FlagRow["status"];
export type PublicFlagKind = FlagRow["flag_kind"];
export type PublicFlagTargetType =
  | "assertion"
  | "source"
  | "fiche_section"
  | "classification";

export interface PublicFlagFilters {
  statuses?: PublicFlagStatus[];
  kinds?: PublicFlagKind[];
  targetTypes?: PublicFlagTargetType[];
}

export interface PublicFlagsPageOptions extends PublicFlagFilters {
  cursor?: string;
  pageSize?: number;
}

export interface PublicFlagTarget {
  type: PublicFlagTargetType;
  id: string;
  label: string;
  entityType: string | null;
  entityId: string | null;
  fieldPath: string | null;
  statement: string | null;
}

export interface PublicFlagListItem {
  id: string;
  publicSlug: string;
  kind: PublicFlagKind;
  status: PublicFlagStatus;
  reasonText: string | null;
  severity: FlagRow["severity"];
  autoGenerated: boolean;
  createdAt: string;
  contributorName: string;
  target: PublicFlagTarget;
}

export interface PublicFlagsPage {
  items: PublicFlagListItem[];
  nextCursor: string | null;
}

interface PublicFlagQueryRow {
  id: string;
  public_slug: string;
  flag_kind: PublicFlagKind;
  status: PublicFlagStatus;
  entity_type: string | null;
  entity_id: string | null;
  reason_text: string | null;
  contributor_id: string | null;
  assertion_id: string | null;
  assertion_field_path: string | null;
  severity: FlagRow["severity"];
  auto_generated: boolean;
  created_at: string;
}

interface AssertionContextRow {
  id: string;
  entity_type: string | null;
  entity_id: string | null;
  field_path: string | null;
  statement: string | null;
}

interface ContributorProfileRow {
  id: string;
  user_id: string | null;
  display_name: string | null;
  public: boolean | null;
}

interface PublicFlagsCursor {
  createdAt: string;
  id: string;
}
const PUBLIC_FLAGS_CURSOR_SCHEMA = z
  .object({
    createdAt: z.string().datetime({ offset: true }),
    id: z.string().uuid(),
  })
  .required();

interface EntityReference {
  entityType: string | null;
  entityId: string | null;
}

const MAX_PAGE_SIZE = 50;
const ANONYMOUS_CONTRIBUTOR_NAME = "";
const FICHE_ENTITY_TYPES = [
  "fiche_section",
  "people",
  "country",
  "language",
  "language_family",
] as const;
const ENTITY_LABEL_CONFIG = {
  source: { table: "sources", column: "title" },
  people: { table: "afrik_peoples", column: "name_main" },
  country: { table: "afrik_countries", column: "name_fr" },
  language: { table: "afrik_languages", column: "name" },
  language_family: {
    table: "afrik_language_families",
    column: "name_fr",
  },
} as const;

function encodeCursor(cursor: PublicFlagsCursor): string {
  return btoa(JSON.stringify(cursor))
    .replaceAll("+", "-")
    .replaceAll("/", "_")
    .replace(/=+$/, "");
}

function decodeCursor(cursor: string): PublicFlagsCursor {
  const base64 = cursor.replaceAll("-", "+").replaceAll("_", "/");
  const padded = base64.padEnd(Math.ceil(base64.length / 4) * 4, "=");

  let value: unknown;
  try {
    value = JSON.parse(atob(padded));
  } catch {
    throw new Error("Invalid public flags cursor");
  }

  const parsed = PUBLIC_FLAGS_CURSOR_SCHEMA.safeParse(value);
  if (!parsed.success) {
    throw new Error("Invalid public flags cursor");
  }

  const { createdAt, id } = parsed.data;
  if (!createdAt || !id) {
    throw new Error("Invalid public flags cursor");
  }

  return { createdAt, id };
}

// @req REQ-014
export function isValidPublicFlagsCursor(cursor: string): boolean {
  try {
    decodeCursor(cursor);
    return true;
  } catch {
    return false;
  }
}

function normalizePageSize(pageSize: number | undefined): number {
  if (!Number.isFinite(pageSize)) return MAX_PAGE_SIZE;

  return Math.min(
    MAX_PAGE_SIZE,
    Math.max(1, Math.floor(pageSize ?? MAX_PAGE_SIZE))
  );
}

function uniqueValues<T>(values: T[] | undefined): T[] {
  return [...new Set(values ?? [])];
}

function getTargetFilter(targetTypes: PublicFlagTargetType[]): string | null {
  if (targetTypes.length === 0) return null;

  const filters: string[] = [];
  if (targetTypes.includes("assertion")) {
    filters.push("assertion_id.not.is.null");
  }

  const entityTypes = targetTypes.flatMap((targetType) => {
    if (targetType === "assertion") return [];
    if (targetType === "fiche_section") return [...FICHE_ENTITY_TYPES];
    return [targetType];
  });
  if (entityTypes.length > 0) {
    filters.push(
      `and(assertion_id.is.null,entity_type.in.(${entityTypes.join(",")}))`
    );
  }

  return filters.join(",");
}

function getContributorName(
  profile: ContributorProfileRow | undefined
): string {
  if (profile?.public === true && profile.display_name?.trim()) {
    return profile.display_name;
  }

  return ANONYMOUS_CONTRIBUTOR_NAME;
}

function getEntityTargetType(entityType: string | null): PublicFlagTargetType {
  if (
    entityType === "source" ||
    entityType === "fiche_section" ||
    entityType === "classification"
  ) {
    return entityType;
  }

  return "fiche_section";
}

async function getAssertionContexts(
  supabase: SupabaseClient,
  assertionIds: string[]
): Promise<Map<string, AssertionContextRow>> {
  if (assertionIds.length === 0) return new Map();

  const { data, error } = await supabase
    .from("assertions")
    .select("id, entity_type, entity_id, field_path, statement")
    .in("id", assertionIds);

  if (error) {
    logger.error("Failed to fetch public flag assertion contexts", error, {
      assertionCount: assertionIds.length,
    });
    return new Map();
  }

  const assertions: AssertionContextRow[] = data ?? [];
  return new Map(assertions.map((assertion) => [assertion.id, assertion]));
}

async function getContributorProfiles(
  supabase: SupabaseClient,
  contributorIds: string[]
): Promise<Map<string, ContributorProfileRow>> {
  if (contributorIds.length === 0) return new Map();

  const idList = contributorIds.join(",");
  const { data, error } = await supabase
    .from("contributor_profiles")
    .select("id, user_id, display_name, public")
    .eq("public", true)
    .or(`id.in.(${idList}),user_id.in.(${idList})`);

  if (error) {
    logger.error("Failed to fetch public flag contributor profiles", error, {
      contributorCount: contributorIds.length,
    });
    return new Map();
  }

  const profiles: ContributorProfileRow[] = data ?? [];
  const profilesByContributorId = new Map<string, ContributorProfileRow>();

  for (const profile of profiles) {
    profilesByContributorId.set(profile.id, profile);
    if (profile.user_id) {
      profilesByContributorId.set(profile.user_id, profile);
    }
  }

  return profilesByContributorId;
}

async function getEntityLabels(
  supabase: SupabaseClient,
  references: EntityReference[]
): Promise<Map<string, string>> {
  const labels = new Map<string, string>();

  await Promise.all(
    Object.entries(ENTITY_LABEL_CONFIG).map(
      async ([entityType, { table, column }]) => {
        const entityIds = uniqueValues(
          references
            .filter((reference) => reference.entityType === entityType)
            .map((reference) => reference.entityId)
            .filter((entityId): entityId is string => entityId !== null)
        );
        if (entityIds.length === 0) return;

        const { data, error } = await supabase
          .from(table)
          .select(`id, ${column}`)
          .in("id", entityIds);

        if (error) {
          logger.error("Failed to fetch public flag entity labels", error, {
            entityType,
            entityCount: entityIds.length,
          });
          return;
        }

        for (const row of data ?? []) {
          const id = String(row.id);
          const label = row[column];
          if (typeof label === "string" && label.trim()) {
            labels.set(`${entityType}:${id}`, label.trim());
          }
        }
      }
    )
  );

  return labels;
}

function resolveEntityLabel(
  labels: Map<string, string>,
  entityType: string | null,
  entityId: string | null,
  fallback: string
): string {
  if (entityType && entityId) {
    const label = labels.get(`${entityType}:${entityId}`);
    if (label) return label;
  }

  return fallback;
}

// @req REQ-014
export async function queryPublicFlagsPage(
  supabase: SupabaseClient,
  options: PublicFlagsPageOptions = {}
): Promise<PublicFlagsPage> {
  const pageSize = normalizePageSize(options.pageSize);
  const statuses = uniqueValues(options.statuses);
  const kinds = uniqueValues(options.kinds);
  const targetTypes = uniqueValues(options.targetTypes);

  let query = supabase
    .from("flags")
    .select(
      "id, public_slug, flag_kind, status, entity_type, entity_id, reason_text, contributor_id, assertion_id, assertion_field_path, severity, auto_generated, created_at"
    );

  if (statuses.length > 0) {
    query = query.in("status", statuses);
  }
  if (kinds.length > 0) {
    query = query.in("flag_kind", kinds);
  }

  const disjunctions: string[] = [];
  const targetFilter = getTargetFilter(targetTypes);
  if (targetFilter) disjunctions.push(targetFilter);

  if (options.cursor) {
    const cursor = decodeCursor(options.cursor);
    disjunctions.push(
      `created_at.lt.${cursor.createdAt},and(created_at.eq.${cursor.createdAt},id.lt.${cursor.id})`
    );
  }

  if (disjunctions.length === 1) {
    query = query.or(disjunctions[0]);
  } else if (disjunctions.length > 1) {
    query = query.or(
      `and(${disjunctions.map((filter) => `or(${filter})`).join(",")})`
    );
  }

  const { data, error } = await query
    .order("created_at", { ascending: false })
    .order("id", { ascending: false })
    .limit(pageSize + 1);

  if (error) {
    logger.error("Failed to fetch public flags page", error, {
      statuses,
      kinds,
      targetTypes,
    });
    throw new Error("Failed to fetch public flags page");
  }

  const rows: PublicFlagQueryRow[] = data ?? [];
  const pageRows = rows.slice(0, pageSize);
  const assertionIds = uniqueValues(
    pageRows
      .map((row) => row.assertion_id)
      .filter((assertionId): assertionId is string => assertionId !== null)
  );
  const contributorIds = uniqueValues(
    pageRows
      .map((row) => row.contributor_id)
      .filter(
        (contributorId): contributorId is string => contributorId !== null
      )
  );

  const [assertionsById, profilesByContributorId] = await Promise.all([
    getAssertionContexts(supabase, assertionIds),
    getContributorProfiles(supabase, contributorIds),
  ]);
  const entityLabels = await getEntityLabels(
    supabase,
    pageRows.map((row) => {
      const assertion = row.assertion_id
        ? assertionsById.get(row.assertion_id)
        : undefined;
      return {
        entityType: assertion?.entity_type ?? row.entity_type,
        entityId: assertion?.entity_id ?? row.entity_id,
      };
    })
  );

  const items = pageRows.map((row): PublicFlagListItem => {
    const assertion = row.assertion_id
      ? assertionsById.get(row.assertion_id)
      : undefined;
    const contributor = row.contributor_id
      ? profilesByContributorId.get(row.contributor_id)
      : undefined;
    const target: PublicFlagTarget = row.assertion_id
      ? {
          type: "assertion",
          id: row.assertion_id,
          label: resolveEntityLabel(
            entityLabels,
            assertion?.entity_type ?? row.entity_type,
            assertion?.entity_id ?? row.entity_id,
            assertion?.statement?.trim() ||
              assertion?.entity_id ||
              row.entity_id ||
              row.assertion_id
          ),
          entityType: assertion?.entity_type ?? row.entity_type,
          entityId: assertion?.entity_id ?? row.entity_id,
          fieldPath: assertion?.field_path ?? row.assertion_field_path ?? null,
          statement: assertion?.statement ?? null,
        }
      : {
          type: getEntityTargetType(row.entity_type),
          id: row.entity_id ?? row.id,
          label: resolveEntityLabel(
            entityLabels,
            row.entity_type,
            row.entity_id,
            row.entity_id ?? row.id
          ),
          entityType: row.entity_type,
          entityId: row.entity_id,
          fieldPath: row.assertion_field_path,
          statement: null,
        };

    return {
      id: row.id,
      publicSlug: row.public_slug,
      kind: row.flag_kind,
      status: row.status,
      reasonText: row.reason_text,
      severity: row.severity,
      autoGenerated: row.auto_generated,
      createdAt: row.created_at,
      contributorName: getContributorName(contributor),
      target,
    };
  });

  const cursorRow = rows.length > pageSize ? pageRows.at(-1) : undefined;

  return {
    items,
    nextCursor: cursorRow
      ? encodeCursor({ createdAt: cursorRow.created_at, id: cursorRow.id })
      : null,
  };
}
